In [1]:
# write first program


## Discussion Questions

What is programming?

What is object-oriented programming (OOP)?

What is an object?
* attributes/properties - information of an object
* methods/functions - actions an object can perform

Ipeirotis: https://github.com/ipeirotis/introduction-to-python/tree/master/notes

### Markdown
Markdown is useful for formatting expository text

# header 1
## header 2
### header 3
#### header 4
##### header 5
##### header 6

*italics*

**bold**

***bold italics***


* bullet points

* bullet points

1. enumeration

2. enumeration

```python
# code formatting
print("Hello world")
```

LaTex math equations: $e^{i\pi} + 1 = 0$

Multi-line equations:
$$\begin{align}
    f(x) = ax^n, n \in \mathbb{Z} \setminus \{0\} &\implies f'(x) = a n x^{n-1}
    \\&\implies
    f^{(m)}(x) = a {n! \over (n-m)!} x^{n-m}
\end{align}$$

## Variables

In [2]:
# variables
celsius = 12
fahrenheit = (celsius * 9/5) + 32

print(celsius, '°C =', fahrenheit, '°F')

12 °C = 53.6 °F


## Primitive Data Types

In [3]:
# integer
x = 1
type(x)

int

In [4]:
# float
x = 1.0
type(x)

float

In [5]:
# string
x = '1.0'
type(x)

str

In [6]:
# boolean
x = True
type(x)

bool

## (Built-in) Data Structures

In [7]:
# set: unordered collection of unqiue elements
x = {1, 2, 3}
type(x)

set

In [8]:
# tuple: immutable, ordered collection
x = (1, 2, 3)
type(x)

tuple

In [9]:
# list: mutable, ordered collection
x = [1, 2, 3]
type(x)

list

In [10]:
# dictionary: key-value pairs with unique keys
x = {'a' : 1, 'b' : 2, 'c' : 3}
type(x)

dict

## Conditions (If Statements)

In [11]:
# conditions: if statements

x = 10

if x < 5:
    print('x is less than 5')

elif x > 5:
    print('x is greater than 5')
    
# isn't something missing?

x is greater than 5


In [12]:
# another example
today = "2021-10-11"

# import datetime package
from datetime import datetime as dt

# some processing
date = dt.strptime(today, '%Y-%M-%d')
dayofweek = date.weekday()
weekdict = {0:'Mon', 1:'Tues', 2:'Wedns', 3:'Thurs', 4:'Fri', 5:'Satur', 6:'Sun'}

# if statement
if dayofweek == 1:
    print(today, "is Taco Tuesday!")
else:
    print(today, "is not Taco Tuesday :( It's a", weekdict[dayofweek]+'day.')

2021-10-11 is not Taco Tuesday :( It's a Monday.


## Iteration (For Loops)

In [13]:
# iterative index
for i in range(11):
    print(i, end=', ')

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 

In [14]:
# repetition with iteration
for _ in range(10):
    print('a rose is', end=' ')

print('...')

a rose is a rose is a rose is a rose is a rose is a rose is a rose is a rose is a rose is a rose is ...


In [15]:
# fibonnaci numbers
fib = [1, 1] # seed

# iterate to create fibonnaci sequence
for _ in range(10):
    fib.append(fib[-1] + fib[-2])

# print each fib number iteratively
for n in fib:
    print(n, end=', ')

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 

## Control Flow (Conditions + Iteration)

In [16]:
# fizzbuzz
n = 20

for i in range(1, n+1):
    
    msg = ''
    
    if i % 5 == 0:
        msg += 'Fizz'
    
    if i % 7 == 0:
        msg += 'Buzz'
    
    if msg == '':
        msg = str(i)
    
    print(msg, end=', ')

1, 2, 3, 4, Fizz, 6, Buzz, 8, 9, Fizz, 11, 12, 13, Buzz, Fizz, 16, 17, 18, 19, Fizz, 

## Functions

In [17]:
# simple example
def hello(name):
    return f'Hello {name}!'

In [18]:
hello('World')

'Hello World!'

## Working with Files

In [19]:
# write file
with open("hello.txt", 'w') as f:
    f.write('Hello world!')
    f.close()

In [20]:
# read files
with open("hello.txt", "r") as f:
    data = f.read()
    f.close()
    
print(data)

Hello world!


In [21]:
# print files in current directory
import os
for file in os.listdir():
    print(file)

.ipynb_checkpoints
A-Overview.ipynb
B-Challenges.ipynb
hello.txt


## Object Classes

In [22]:
class Person:
    
    def __init__(self, name, age, job):
        
        self.name = name
        self.age = age
        self.job = job
    
    def describe(self):

        return f'My name is {self.name}. I am a {self.age}-year-old {self.job}.'
        
    def intro(self, other):
        
        return f'Nice to meet you {other}! My name is {self.name}.'

In [23]:
me = Person('Jack', 25, 'economics student')
me.describe()

'My name is Jack. I am a 25-year-old economics student.'

In [24]:
me.intro("Jill")

'Nice to meet you Jill! My name is Jack.'

## Packages

In [25]:
import numpy as np
x = np.array([[1, 2],
          [3, 4]
         ])

print(x) # matrix
print(x.T) # transpose
print(x@x) # matrix mult

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 7 10]
 [15 22]]


In [26]:
import sympy as sp

a, b, c, d = sp.symbols('a, b, c, d')

x = sp.Matrix([[a, b],
               [c, d]])
display(x)
display(x@x)

Matrix([
[a, b],
[c, d]])

Matrix([
[a**2 + b*c,  a*b + b*d],
[ a*c + c*d, b*c + d**2]])

In [27]:
import pandas as pd

# read AAPL price data from Yahoo Finance
url = 'https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=345427200&period2=1633996800&interval=1d&events=history&includeAdjustedClose=true'
df = pd.read_csv(url)
df

Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.100600   
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.095352   
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.088353   
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.090540   
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.093165   
...           ...         ...         ...         ...         ...         ...   
10290  2021-10-05  139.490005  142.240005  139.360001  141.110001  141.110001   
10291  2021-10-06  139.470001  142.149994  138.369995  142.000000  142.000000   
10292  2021-10-07  143.059998  144.220001  142.720001  143.289993  143.289993   
10293  2021-10-08  144.029999  144.179993  142.559998  142.899994  142.899994   
10294  2021-10-11  142.270004  144.809998  141.809998  142.809998  142.809998   

          Volume  
0      469033600  
1      175884800  
2      105728000  
3       86441600  
4       73449600  
...          ...  
10290   80861100  
10291   83221100  
10292   61732700  
10293   58718700  
10294   63012662  

[10295 rows x 7 columns]